### ISSUE TITLE
Tailwind CSS V4 classes are NOT APPLIED in EJS templates

### ISSUE THREAD

**Issue by IgorArnaut** [mde/ejs#785]
I'm working on an Express project. I installed Tailwind CSS v4.1. I've put Tailwind classes inside EJS templates. None of those classes didn't work.

views/index.ejs:
```EJS
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="/stylesheets/style.css" />
  </head>
  <body class="bg-amber-500 text-white">
    <%= title %>
  </body>
</html>
```

public/stylesheets/style.css (created via Tailwind CLI):
```CSS
/*! tailwindcss v4.1.4 | MIT License | https://tailwindcss.com */
@layer theme, base, components, utilities;
@layer theme {
  :root, :host {
    --font-sans: ui-sans-serif, system-ui, sans-serif, "Apple Color Emoji",
      "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
    --font-mono: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono",
      "Courier New", monospace;
    --color-gray-950: oklch(13% 0.028 261.692);
    --text-2xl: 1.5rem;
    --text-2xl--line-height: calc(2 / 1.5);
    --default-font-family: var(--font-sans);
    --default-mono-font-family: var(--font-mono);
  }
}
/* and so on */
```
app.js:
```JS
import cookieParser from "cookie-parser";
import express, { json, urlencoded } from "express";
import createError from "http-errors";
import logger from "morgan";
import { join } from "path";

import indexRouter from "./routes/index.js";
import listingsRouter from "./routes/listings.js";

const app = express();
const __dirname = import.meta.dirname;

// view engine setup
app.set("view engine", "ejs");
app.set("views", join(__dirname, "views"));

app.use(cookieParser());
app.use(express.static(join(__dirname, "public")));
app.use(json());
app.use(logger("dev"));
app.use(urlencoded({ extended: false }));

app.use("/", indexRouter);
app.use("/listings", listingsRouter);

// catch 404 and forward to error handler
app.use((_req, _res, next) => next(createError(404)));

// error handler
app.use(function (err, req, res, _next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get("env") === "development" ? err : {};

  // render the error page
  res.status(err.status || 500);
  res.render("error");
});

export default app;
```
Nothing is changed on the page.
